### ISSUE TITLE
Reading in VCF's

### ISSUE THREAD

**Issue by Euphrasiologist** [EvolEcolGroup/tidypopgen#6]
I believe you already have the functionality to do this? Would require a function like this:

```R
read_vcf <- function(file, quiet = TRUE, ...) {
  inner_vcf <- vcfR::read.vcfR(file = file, verbose = !quiet, ...)
  as_gen_tibble(inner_vcf)
}
```

Would something like that be sufficient?

Cheers,
M

**Comment by dramanica** [comment]
I have written a C++ parser that is lean and mean, and is, in principle, quite a bit faster than the current parsing with `vcfR`. It is in the branch `vcf_fast`. But it needs some testing (there is still a bug when reading vcf in multiple passes that needs fixing).
